*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 06.07.2019 at 09:33:13
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_CACT_V.................................*
FORM GET_DATA_/GDA/SDM_CACT_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_CACT WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_CACT_V .
/GDA/SDM_CACT_V-MANDT =
/GDA/SDM_CACT-MANDT .
/GDA/SDM_CACT_V-LANGU =
/GDA/SDM_CACT-LANGU .
/GDA/SDM_CACT_V-OBJECT_TYPE =
/GDA/SDM_CACT-OBJECT_TYPE .
/GDA/SDM_CACT_V-OBJECT_VIEW =
/GDA/SDM_CACT-OBJECT_VIEW .
/GDA/SDM_CACT_V-ACTIONID =
/GDA/SDM_CACT-ACTIONID .
/GDA/SDM_CACT_V-FCODE =
/GDA/SDM_CACT-FCODE .
/GDA/SDM_CACT_V-REFRESH =
/GDA/SDM_CACT-REFRESH .
/GDA/SDM_CACT_V-INACTIVE =
/GDA/SDM_CACT-INACTIVE .
    SELECT SINGLE * FROM /GDA/SDM_CACTT WHERE
LANGU = /GDA/SDM_CACT-LANGU AND
OBJECT_TYPE = /GDA/SDM_CACT-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_CACT-OBJECT_VIEW AND
ACTIONID = /GDA/SDM_CACT-ACTIONID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/GDA/SDM_CACT_V-MENUTEXT =
/GDA/SDM_CACTT-MENUTEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /GDA/SDM_CACT_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_CACT_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_CACT_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_CACT_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_CACT WHERE
  LANGU = /GDA/SDM_CACT_V-LANGU AND
  OBJECT_TYPE = /GDA/SDM_CACT_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_CACT_V-OBJECT_VIEW AND
  ACTIONID = /GDA/SDM_CACT_V-ACTIONID .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_CACT .
    ENDIF.
    DELETE FROM /GDA/SDM_CACTT WHERE
    LANGU = /GDA/SDM_CACT-LANGU AND
    OBJECT_TYPE = /GDA/SDM_CACT-OBJECT_TYPE AND
    OBJECT_VIEW = /GDA/SDM_CACT-OBJECT_VIEW AND
    ACTIONID = /GDA/SDM_CACT-ACTIONID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_CACT WHERE
  LANGU = /GDA/SDM_CACT_V-LANGU AND
  OBJECT_TYPE = /GDA/SDM_CACT_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_CACT_V-OBJECT_VIEW AND
  ACTIONID = /GDA/SDM_CACT_V-ACTIONID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_CACT.
    ENDIF.
/GDA/SDM_CACT-MANDT =
/GDA/SDM_CACT_V-MANDT .
/GDA/SDM_CACT-LANGU =
/GDA/SDM_CACT_V-LANGU .
/GDA/SDM_CACT-OBJECT_TYPE =
/GDA/SDM_CACT_V-OBJECT_TYPE .
/GDA/SDM_CACT-OBJECT_VIEW =
/GDA/SDM_CACT_V-OBJECT_VIEW .
/GDA/SDM_CACT-ACTIONID =
/GDA/SDM_CACT_V-ACTIONID .
/GDA/SDM_CACT-FCODE =
/GDA/SDM_CACT_V-FCODE .
/GDA/SDM_CACT-REFRESH =
/GDA/SDM_CACT_V-REFRESH .
/GDA/SDM_CACT-INACTIVE =
/GDA/SDM_CACT_V-INACTIVE .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_CACT .
    ELSE.
    INSERT /GDA/SDM_CACT .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_CACTT WHERE
    LANGU = /GDA/SDM_CACT-LANGU AND
    OBJECT_TYPE = /GDA/SDM_CACT-OBJECT_TYPE AND
    OBJECT_VIEW = /GDA/SDM_CACT-OBJECT_VIEW AND
    ACTIONID = /GDA/SDM_CACT-ACTIONID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /GDA/SDM_CACTT.
/GDA/SDM_CACTT-LANGU =
/GDA/SDM_CACT-LANGU .
/GDA/SDM_CACTT-OBJECT_TYPE =
/GDA/SDM_CACT-OBJECT_TYPE .
/GDA/SDM_CACTT-OBJECT_VIEW =
/GDA/SDM_CACT-OBJECT_VIEW .
/GDA/SDM_CACTT-ACTIONID =
/GDA/SDM_CACT-ACTIONID .
/GDA/SDM_CACTT-SPRAS =
SY-LANGU .
      ENDIF.
/GDA/SDM_CACTT-MENUTEXT =
/GDA/SDM_CACT_V-MENUTEXT .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_CACTT .
    ELSE.
    INSERT /GDA/SDM_CACTT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_CACT_V-UPD_FLAG,
STATUS_/GDA/SDM_CACT_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_CACT_V.
  SELECT SINGLE * FROM /GDA/SDM_CACT WHERE
LANGU = /GDA/SDM_CACT_V-LANGU AND
OBJECT_TYPE = /GDA/SDM_CACT_V-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_CACT_V-OBJECT_VIEW AND
ACTIONID = /GDA/SDM_CACT_V-ACTIONID .
/GDA/SDM_CACT_V-MANDT =
/GDA/SDM_CACT-MANDT .
/GDA/SDM_CACT_V-LANGU =
/GDA/SDM_CACT-LANGU .
/GDA/SDM_CACT_V-OBJECT_TYPE =
/GDA/SDM_CACT-OBJECT_TYPE .
/GDA/SDM_CACT_V-OBJECT_VIEW =
/GDA/SDM_CACT-OBJECT_VIEW .
/GDA/SDM_CACT_V-ACTIONID =
/GDA/SDM_CACT-ACTIONID .
/GDA/SDM_CACT_V-FCODE =
/GDA/SDM_CACT-FCODE .
/GDA/SDM_CACT_V-REFRESH =
/GDA/SDM_CACT-REFRESH .
/GDA/SDM_CACT_V-INACTIVE =
/GDA/SDM_CACT-INACTIVE .
    SELECT SINGLE * FROM /GDA/SDM_CACTT WHERE
LANGU = /GDA/SDM_CACT-LANGU AND
OBJECT_TYPE = /GDA/SDM_CACT-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_CACT-OBJECT_VIEW AND
ACTIONID = /GDA/SDM_CACT-ACTIONID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/GDA/SDM_CACT_V-MENUTEXT =
/GDA/SDM_CACTT-MENUTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /GDA/SDM_CACT_V-MENUTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_CACT_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_CACT_V-LANGU TO
/GDA/SDM_CACT-LANGU .
MOVE /GDA/SDM_CACT_V-OBJECT_TYPE TO
/GDA/SDM_CACT-OBJECT_TYPE .
MOVE /GDA/SDM_CACT_V-OBJECT_VIEW TO
/GDA/SDM_CACT-OBJECT_VIEW .
MOVE /GDA/SDM_CACT_V-ACTIONID TO
/GDA/SDM_CACT-ACTIONID .
MOVE /GDA/SDM_CACT_V-MANDT TO
/GDA/SDM_CACT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_CACT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_CACT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_CACT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /GDA/SDM_CACT-LANGU TO
/GDA/SDM_CACTT-LANGU .
MOVE /GDA/SDM_CACT-OBJECT_TYPE TO
/GDA/SDM_CACTT-OBJECT_TYPE .
MOVE /GDA/SDM_CACT-OBJECT_VIEW TO
/GDA/SDM_CACTT-OBJECT_VIEW .
MOVE /GDA/SDM_CACT-ACTIONID TO
/GDA/SDM_CACTT-ACTIONID .
MOVE SY-LANGU TO
/GDA/SDM_CACTT-SPRAS .
MOVE /GDA/SDM_CACT_V-MANDT TO
/GDA/SDM_CACTT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_CACTT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_CACTT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_CACTT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_OBJ_V..................................*
FORM GET_DATA_/GDA/SDM_OBJ_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_OBJ WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_OBJ_V .
/GDA/SDM_OBJ_V-MANDT =
/GDA/SDM_OBJ-MANDT .
/GDA/SDM_OBJ_V-SDM_OBJECT =
/GDA/SDM_OBJ-SDM_OBJECT .
/GDA/SDM_OBJ_V-SDM_OBJECT_ID =
/GDA/SDM_OBJ-SDM_OBJECT_ID .
<VIM_TOTAL_STRUC> = /GDA/SDM_OBJ_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_OBJ_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_OBJ_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_OBJ_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_OBJ WHERE
  SDM_OBJECT_ID = /GDA/SDM_OBJ_V-SDM_OBJECT_ID AND
  SDM_OBJECT = /GDA/SDM_OBJ_V-SDM_OBJECT .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_OBJ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_OBJ WHERE
  SDM_OBJECT_ID = /GDA/SDM_OBJ_V-SDM_OBJECT_ID AND
  SDM_OBJECT = /GDA/SDM_OBJ_V-SDM_OBJECT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_OBJ.
    ENDIF.
/GDA/SDM_OBJ-MANDT =
/GDA/SDM_OBJ_V-MANDT .
/GDA/SDM_OBJ-SDM_OBJECT =
/GDA/SDM_OBJ_V-SDM_OBJECT .
/GDA/SDM_OBJ-SDM_OBJECT_ID =
/GDA/SDM_OBJ_V-SDM_OBJECT_ID .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_OBJ .
    ELSE.
    INSERT /GDA/SDM_OBJ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_OBJ_V-UPD_FLAG,
STATUS_/GDA/SDM_OBJ_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_OBJ_V.
  SELECT SINGLE * FROM /GDA/SDM_OBJ WHERE
SDM_OBJECT_ID = /GDA/SDM_OBJ_V-SDM_OBJECT_ID AND
SDM_OBJECT = /GDA/SDM_OBJ_V-SDM_OBJECT .
/GDA/SDM_OBJ_V-MANDT =
/GDA/SDM_OBJ-MANDT .
/GDA/SDM_OBJ_V-SDM_OBJECT =
/GDA/SDM_OBJ-SDM_OBJECT .
/GDA/SDM_OBJ_V-SDM_OBJECT_ID =
/GDA/SDM_OBJ-SDM_OBJECT_ID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_OBJ_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_OBJ_V-SDM_OBJECT_ID TO
/GDA/SDM_OBJ-SDM_OBJECT_ID .
MOVE /GDA/SDM_OBJ_V-SDM_OBJECT TO
/GDA/SDM_OBJ-SDM_OBJECT .
MOVE /GDA/SDM_OBJ_V-MANDT TO
/GDA/SDM_OBJ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_OBJ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_OBJ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_OBJ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_STP3_V.................................*
FORM GET_DATA_/GDA/SDM_STP3_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_SETUP3 WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_STP3_V .
/GDA/SDM_STP3_V-MANDT =
/GDA/SDM_SETUP3-MANDT .
/GDA/SDM_STP3_V-OBJECT_TYPE =
/GDA/SDM_SETUP3-OBJECT_TYPE .
/GDA/SDM_STP3_V-OBJECT_VIEW =
/GDA/SDM_SETUP3-OBJECT_VIEW .
/GDA/SDM_STP3_V-OBJECT_VIEW_D =
/GDA/SDM_SETUP3-OBJECT_VIEW_D .
/GDA/SDM_STP3_V-OBJECT_VIEW_O =
/GDA/SDM_SETUP3-OBJECT_VIEW_O .
/GDA/SDM_STP3_V-STATUS =
/GDA/SDM_SETUP3-STATUS .
/GDA/SDM_STP3_V-TREE =
/GDA/SDM_SETUP3-TREE .
/GDA/SDM_STP3_V-ORD =
/GDA/SDM_SETUP3-ORD .
<VIM_TOTAL_STRUC> = /GDA/SDM_STP3_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_STP3_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_STP3_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_STP3_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP3 WHERE
  OBJECT_TYPE = /GDA/SDM_STP3_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP3_V-OBJECT_VIEW .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_SETUP3 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP3 WHERE
  OBJECT_TYPE = /GDA/SDM_STP3_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP3_V-OBJECT_VIEW .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_SETUP3.
    ENDIF.
/GDA/SDM_SETUP3-MANDT =
/GDA/SDM_STP3_V-MANDT .
/GDA/SDM_SETUP3-OBJECT_TYPE =
/GDA/SDM_STP3_V-OBJECT_TYPE .
/GDA/SDM_SETUP3-OBJECT_VIEW =
/GDA/SDM_STP3_V-OBJECT_VIEW .
/GDA/SDM_SETUP3-OBJECT_VIEW_D =
/GDA/SDM_STP3_V-OBJECT_VIEW_D .
/GDA/SDM_SETUP3-OBJECT_VIEW_O =
/GDA/SDM_STP3_V-OBJECT_VIEW_O .
/GDA/SDM_SETUP3-STATUS =
/GDA/SDM_STP3_V-STATUS .
/GDA/SDM_SETUP3-TREE =
/GDA/SDM_STP3_V-TREE .
/GDA/SDM_SETUP3-ORD =
/GDA/SDM_STP3_V-ORD .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_SETUP3 .
    ELSE.
    INSERT /GDA/SDM_SETUP3 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_STP3_V-UPD_FLAG,
STATUS_/GDA/SDM_STP3_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_STP3_V.
  SELECT SINGLE * FROM /GDA/SDM_SETUP3 WHERE
OBJECT_TYPE = /GDA/SDM_STP3_V-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_STP3_V-OBJECT_VIEW .
/GDA/SDM_STP3_V-MANDT =
/GDA/SDM_SETUP3-MANDT .
/GDA/SDM_STP3_V-OBJECT_TYPE =
/GDA/SDM_SETUP3-OBJECT_TYPE .
/GDA/SDM_STP3_V-OBJECT_VIEW =
/GDA/SDM_SETUP3-OBJECT_VIEW .
/GDA/SDM_STP3_V-OBJECT_VIEW_D =
/GDA/SDM_SETUP3-OBJECT_VIEW_D .
/GDA/SDM_STP3_V-OBJECT_VIEW_O =
/GDA/SDM_SETUP3-OBJECT_VIEW_O .
/GDA/SDM_STP3_V-STATUS =
/GDA/SDM_SETUP3-STATUS .
/GDA/SDM_STP3_V-TREE =
/GDA/SDM_SETUP3-TREE .
/GDA/SDM_STP3_V-ORD =
/GDA/SDM_SETUP3-ORD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_STP3_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_STP3_V-OBJECT_TYPE TO
/GDA/SDM_SETUP3-OBJECT_TYPE .
MOVE /GDA/SDM_STP3_V-OBJECT_VIEW TO
/GDA/SDM_SETUP3-OBJECT_VIEW .
MOVE /GDA/SDM_STP3_V-MANDT TO
/GDA/SDM_SETUP3-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_SETUP3'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_SETUP3 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_SETUP3'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_STP4_V.................................*
FORM GET_DATA_/GDA/SDM_STP4_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_SETUP4 WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_STP4_V .
/GDA/SDM_STP4_V-MANDT =
/GDA/SDM_SETUP4-MANDT .
/GDA/SDM_STP4_V-OBJECT_TYPE =
/GDA/SDM_SETUP4-OBJECT_TYPE .
/GDA/SDM_STP4_V-OBJECT_VIEW =
/GDA/SDM_SETUP4-OBJECT_VIEW .
/GDA/SDM_STP4_V-TABNAME =
/GDA/SDM_SETUP4-TABNAME .
/GDA/SDM_STP4_V-FIELD =
/GDA/SDM_SETUP4-FIELD .
/GDA/SDM_STP4_V-ORD =
/GDA/SDM_SETUP4-ORD .
/GDA/SDM_STP4_V-OUTP =
/GDA/SDM_SETUP4-OUTP .
/GDA/SDM_STP4_V-DEFAULT_ALL =
/GDA/SDM_SETUP4-DEFAULT_ALL .
<VIM_TOTAL_STRUC> = /GDA/SDM_STP4_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_STP4_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_STP4_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_STP4_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP4 WHERE
  OBJECT_TYPE = /GDA/SDM_STP4_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP4_V-OBJECT_VIEW AND
  FIELD = /GDA/SDM_STP4_V-FIELD AND
  TABNAME = /GDA/SDM_STP4_V-TABNAME .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_SETUP4 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP4 WHERE
  OBJECT_TYPE = /GDA/SDM_STP4_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP4_V-OBJECT_VIEW AND
  FIELD = /GDA/SDM_STP4_V-FIELD AND
  TABNAME = /GDA/SDM_STP4_V-TABNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_SETUP4.
    ENDIF.
/GDA/SDM_SETUP4-MANDT =
/GDA/SDM_STP4_V-MANDT .
/GDA/SDM_SETUP4-OBJECT_TYPE =
/GDA/SDM_STP4_V-OBJECT_TYPE .
/GDA/SDM_SETUP4-OBJECT_VIEW =
/GDA/SDM_STP4_V-OBJECT_VIEW .
/GDA/SDM_SETUP4-TABNAME =
/GDA/SDM_STP4_V-TABNAME .
/GDA/SDM_SETUP4-FIELD =
/GDA/SDM_STP4_V-FIELD .
/GDA/SDM_SETUP4-ORD =
/GDA/SDM_STP4_V-ORD .
/GDA/SDM_SETUP4-OUTP =
/GDA/SDM_STP4_V-OUTP .
/GDA/SDM_SETUP4-DEFAULT_ALL =
/GDA/SDM_STP4_V-DEFAULT_ALL .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_SETUP4 .
    ELSE.
    INSERT /GDA/SDM_SETUP4 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_STP4_V-UPD_FLAG,
STATUS_/GDA/SDM_STP4_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_STP4_V.
  SELECT SINGLE * FROM /GDA/SDM_SETUP4 WHERE
OBJECT_TYPE = /GDA/SDM_STP4_V-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_STP4_V-OBJECT_VIEW AND
FIELD = /GDA/SDM_STP4_V-FIELD AND
TABNAME = /GDA/SDM_STP4_V-TABNAME .
/GDA/SDM_STP4_V-MANDT =
/GDA/SDM_SETUP4-MANDT .
/GDA/SDM_STP4_V-OBJECT_TYPE =
/GDA/SDM_SETUP4-OBJECT_TYPE .
/GDA/SDM_STP4_V-OBJECT_VIEW =
/GDA/SDM_SETUP4-OBJECT_VIEW .
/GDA/SDM_STP4_V-TABNAME =
/GDA/SDM_SETUP4-TABNAME .
/GDA/SDM_STP4_V-FIELD =
/GDA/SDM_SETUP4-FIELD .
/GDA/SDM_STP4_V-ORD =
/GDA/SDM_SETUP4-ORD .
/GDA/SDM_STP4_V-OUTP =
/GDA/SDM_SETUP4-OUTP .
/GDA/SDM_STP4_V-DEFAULT_ALL =
/GDA/SDM_SETUP4-DEFAULT_ALL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_STP4_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_STP4_V-OBJECT_TYPE TO
/GDA/SDM_SETUP4-OBJECT_TYPE .
MOVE /GDA/SDM_STP4_V-OBJECT_VIEW TO
/GDA/SDM_SETUP4-OBJECT_VIEW .
MOVE /GDA/SDM_STP4_V-FIELD TO
/GDA/SDM_SETUP4-FIELD .
MOVE /GDA/SDM_STP4_V-TABNAME TO
/GDA/SDM_SETUP4-TABNAME .
MOVE /GDA/SDM_STP4_V-MANDT TO
/GDA/SDM_SETUP4-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_SETUP4'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_SETUP4 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_SETUP4'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_STP5_V.................................*
FORM GET_DATA_/GDA/SDM_STP5_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_SETUP5 WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_STP5_V .
/GDA/SDM_STP5_V-MANDT =
/GDA/SDM_SETUP5-MANDT .
/GDA/SDM_STP5_V-OBJECT_TYPE =
/GDA/SDM_SETUP5-OBJECT_TYPE .
/GDA/SDM_STP5_V-OBJECT_VIEW =
/GDA/SDM_SETUP5-OBJECT_VIEW .
/GDA/SDM_STP5_V-TABNAME =
/GDA/SDM_SETUP5-TABNAME .
/GDA/SDM_STP5_V-NODE_LEVEL =
/GDA/SDM_SETUP5-NODE_LEVEL .
/GDA/SDM_STP5_V-NODE_LEVEL2 =
/GDA/SDM_SETUP5-NODE_LEVEL2 .
/GDA/SDM_STP5_V-NODE_LEVEL3 =
/GDA/SDM_SETUP5-NODE_LEVEL3 .
/GDA/SDM_STP5_V-SEQ =
/GDA/SDM_SETUP5-SEQ .
<VIM_TOTAL_STRUC> = /GDA/SDM_STP5_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_STP5_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_STP5_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_STP5_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP5 WHERE
  OBJECT_TYPE = /GDA/SDM_STP5_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP5_V-OBJECT_VIEW AND
  TABNAME = /GDA/SDM_STP5_V-TABNAME .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_SETUP5 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP5 WHERE
  OBJECT_TYPE = /GDA/SDM_STP5_V-OBJECT_TYPE AND
  OBJECT_VIEW = /GDA/SDM_STP5_V-OBJECT_VIEW AND
  TABNAME = /GDA/SDM_STP5_V-TABNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_SETUP5.
    ENDIF.
/GDA/SDM_SETUP5-MANDT =
/GDA/SDM_STP5_V-MANDT .
/GDA/SDM_SETUP5-OBJECT_TYPE =
/GDA/SDM_STP5_V-OBJECT_TYPE .
/GDA/SDM_SETUP5-OBJECT_VIEW =
/GDA/SDM_STP5_V-OBJECT_VIEW .
/GDA/SDM_SETUP5-TABNAME =
/GDA/SDM_STP5_V-TABNAME .
/GDA/SDM_SETUP5-NODE_LEVEL =
/GDA/SDM_STP5_V-NODE_LEVEL .
/GDA/SDM_SETUP5-NODE_LEVEL2 =
/GDA/SDM_STP5_V-NODE_LEVEL2 .
/GDA/SDM_SETUP5-NODE_LEVEL3 =
/GDA/SDM_STP5_V-NODE_LEVEL3 .
/GDA/SDM_SETUP5-SEQ =
/GDA/SDM_STP5_V-SEQ .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_SETUP5 .
    ELSE.
    INSERT /GDA/SDM_SETUP5 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_STP5_V-UPD_FLAG,
STATUS_/GDA/SDM_STP5_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_STP5_V.
  SELECT SINGLE * FROM /GDA/SDM_SETUP5 WHERE
OBJECT_TYPE = /GDA/SDM_STP5_V-OBJECT_TYPE AND
OBJECT_VIEW = /GDA/SDM_STP5_V-OBJECT_VIEW AND
TABNAME = /GDA/SDM_STP5_V-TABNAME .
/GDA/SDM_STP5_V-MANDT =
/GDA/SDM_SETUP5-MANDT .
/GDA/SDM_STP5_V-OBJECT_TYPE =
/GDA/SDM_SETUP5-OBJECT_TYPE .
/GDA/SDM_STP5_V-OBJECT_VIEW =
/GDA/SDM_SETUP5-OBJECT_VIEW .
/GDA/SDM_STP5_V-TABNAME =
/GDA/SDM_SETUP5-TABNAME .
/GDA/SDM_STP5_V-NODE_LEVEL =
/GDA/SDM_SETUP5-NODE_LEVEL .
/GDA/SDM_STP5_V-NODE_LEVEL2 =
/GDA/SDM_SETUP5-NODE_LEVEL2 .
/GDA/SDM_STP5_V-NODE_LEVEL3 =
/GDA/SDM_SETUP5-NODE_LEVEL3 .
/GDA/SDM_STP5_V-SEQ =
/GDA/SDM_SETUP5-SEQ .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_STP5_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_STP5_V-OBJECT_TYPE TO
/GDA/SDM_SETUP5-OBJECT_TYPE .
MOVE /GDA/SDM_STP5_V-OBJECT_VIEW TO
/GDA/SDM_SETUP5-OBJECT_VIEW .
MOVE /GDA/SDM_STP5_V-TABNAME TO
/GDA/SDM_SETUP5-TABNAME .
MOVE /GDA/SDM_STP5_V-MANDT TO
/GDA/SDM_SETUP5-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_SETUP5'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_SETUP5 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_SETUP5'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /GDA/SDM_STP8_V.................................*
FORM GET_DATA_/GDA/SDM_STP8_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /GDA/SDM_SETUP8 WHERE
(VIM_WHERETAB) .
    CLEAR /GDA/SDM_STP8_V .
/GDA/SDM_STP8_V-MANDT =
/GDA/SDM_SETUP8-MANDT .
/GDA/SDM_STP8_V-SDM_OBJECT =
/GDA/SDM_SETUP8-SDM_OBJECT .
/GDA/SDM_STP8_V-ARBGB =
/GDA/SDM_SETUP8-ARBGB .
<VIM_TOTAL_STRUC> = /GDA/SDM_STP8_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/GDA/SDM_STP8_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /GDA/SDM_STP8_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/GDA/SDM_STP8_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP8 WHERE
  SDM_OBJECT = /GDA/SDM_STP8_V-SDM_OBJECT AND
  ARBGB = /GDA/SDM_STP8_V-ARBGB .
    IF SY-SUBRC = 0.
    DELETE /GDA/SDM_SETUP8 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /GDA/SDM_SETUP8 WHERE
  SDM_OBJECT = /GDA/SDM_STP8_V-SDM_OBJECT AND
  ARBGB = /GDA/SDM_STP8_V-ARBGB .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /GDA/SDM_SETUP8.
    ENDIF.
/GDA/SDM_SETUP8-MANDT =
/GDA/SDM_STP8_V-MANDT .
/GDA/SDM_SETUP8-SDM_OBJECT =
/GDA/SDM_STP8_V-SDM_OBJECT .
/GDA/SDM_SETUP8-ARBGB =
/GDA/SDM_STP8_V-ARBGB .
    IF SY-SUBRC = 0.
    UPDATE /GDA/SDM_SETUP8 .
    ELSE.
    INSERT /GDA/SDM_SETUP8 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/GDA/SDM_STP8_V-UPD_FLAG,
STATUS_/GDA/SDM_STP8_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/GDA/SDM_STP8_V.
  SELECT SINGLE * FROM /GDA/SDM_SETUP8 WHERE
SDM_OBJECT = /GDA/SDM_STP8_V-SDM_OBJECT AND
ARBGB = /GDA/SDM_STP8_V-ARBGB .
/GDA/SDM_STP8_V-MANDT =
/GDA/SDM_SETUP8-MANDT .
/GDA/SDM_STP8_V-SDM_OBJECT =
/GDA/SDM_SETUP8-SDM_OBJECT .
/GDA/SDM_STP8_V-ARBGB =
/GDA/SDM_SETUP8-ARBGB .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/GDA/SDM_STP8_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /GDA/SDM_STP8_V-SDM_OBJECT TO
/GDA/SDM_SETUP8-SDM_OBJECT .
MOVE /GDA/SDM_STP8_V-ARBGB TO
/GDA/SDM_SETUP8-ARBGB .
MOVE /GDA/SDM_STP8_V-MANDT TO
/GDA/SDM_SETUP8-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/GDA/SDM_SETUP8'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /GDA/SDM_SETUP8 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/GDA/SDM_SETUP8'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
