PARAMETERS:P_CUST1 TYPE C AS CHECKBOX DEFAULT 'X'. "Check Plant Extensio
PARAMETERS:P_CUST2 TYPE C AS CHECKBOX DEFAULT 'X'. "Check Plant Extensio
PARAMETERS:P_CUST3 TYPE C AS CHECKBOX DEFAULT 'X'. "Check Plant Extensio
